"""Initial migration

Revision ID: 645de8d15833
Revises: 
Create Date: 2025-04-20 10:14:05.059139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645de8d15833'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sso_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sso_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('ldap_accounts',
    sa.Column('kdc_hosts', sa.String(length=255), nullable=True),
    sa.Column('realm', sa.String(length=255), nullable=True),
    sa.Column('kadmin_server', sa.String(length=255), nullable=True),
    sa.Column('kadmin_principal', sa.String(length=255), nullable=True),
    sa.Column('kadmin_password', sa.LargeBinary(), nullable=True),
    sa.Column('admin_dn', sa.String(length=255), nullable=True),
    sa.Column('ldap_url', sa.String(length=255), nullable=True),
    sa.Column('container_dn', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sso_user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['sso_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('kadmin_principal'),
    sa.UniqueConstraint('kadmin_principal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ldap_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
